# Generated by Django 5.1.6 on 2025-03-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1)),
                ('bathrooms', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1)),
                ('wifi', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/images/')),
                ('city', models.CharField(choices=[('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Aswan', 'Aswan'), ('Giza', 'Giza'), ('Hurgada', 'Hurgada'), ('Luxor', 'Luxor'), ('Sharm El-Shakh', 'Sharm El-Shakh')], default='Cairo', max_length=100)),
                ('light', models.CharField(max_length=100)),
            ],
        ),
    ]
