# Generated by Django 5.1.6 on 2025-03-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_light_hotel_created_at'),
    ]

    operations = [
    ]
