# Generated by Django 5.1.6 on 2025-03-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_category_alter_hotel_bathrooms_alter_hotel_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels.category'),
            preserve_default=False,
        ),
    ]
