# Generated by Django 5.1.6 on 2025-03-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_hotel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='bathrooms',
            new_name='baths',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='rooms',
            new_name='beds',
        ),
    ]
