# Generated by Django 5.1.6 on 2025-03-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_rename_bathrooms_hotel_baths_rename_rooms_hotel_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
